//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignatura
    {
        public int idAsignatura { get; set; }
        public string nombreAsignatura { get; set; }
        public string codigoAsignatura { get; set; }
        public Nullable<int> idArea { get; set; }
        public int creditos { get; set; }
        public Nullable<int> idCarrera { get; set; }
        public bool esActivo { get; set; }
        public string Icon { get; set; }
        public string Color { get; set; }
    }
}
