//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignatura
    {
        public int idAsignatura { get; set; }
        public string nombreAsignatura { get; set; }
        public string codigoAsignatura { get; set; }
        public Nullable<int> idArea { get; set; }
        public int creditos { get; set; }
        public Nullable<int> idCarrera { get; set; }
        public bool esActivo { get; set; }
    }
}
