//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignatura_Pensum
    {
        public int idAsignaturaPensum { get; set; }
        public int idAsignatura { get; set; }
        public int idPensum { get; set; }
        public int idTrimestre { get; set; }
    }
}
