//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrera
    {
        public int idCarrera { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int duracionTrimestres { get; set; }
        public int creditos { get; set; }
        public int idArea { get; set; }
        public bool esActivo { get; set; }
    }
}
