//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstatusSolicitudesSoporte
    {
        public int idEstatus { get; set; }
        public string Nombre { get; set; }
        public bool FinalizaSolicitud { get; set; }
        public string Severity { get; set; }
    }
}
