//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public int idEstudiante { get; set; }
        public int idUsuario { get; set; }
        public int idCarrera { get; set; }
        public int trimestresCursados { get; set; }
        public int asignaturasAprobadas { get; set; }
        public int idPensum { get; set; }
    }
}
