//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public int idEstudiante { get; set; }
        public int idUsuario { get; set; }
        public int idCarrera { get; set; }
        public int trimestresCursados { get; set; }
        public int asignaturasAprobadas { get; set; }
        public int idPensum { get; set; }
    }
}
