//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listado_Estudiantes
    {
        public int idListadoEstudiante { get; set; }
        public int idSeccion { get; set; }
        public int idEstudiante { get; set; }
        public int idPeriodo { get; set; }
        public string anioPeriodo { get; set; }
    }
}
