//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listado_Estudiantes
    {
        public int idListadoEstudiante { get; set; }
        public int idSeccion { get; set; }
        public int idEstudiante { get; set; }
        public int idPeriodo { get; set; }
    }
}
