//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maestro
    {
        public int idMaestro { get; set; }
        public int idUsuario { get; set; }
        public string credencial { get; set; }
        public int idArea { get; set; }
    }
}
