//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pensum
    {
        public int idPensum { get; set; }
        public string nombrePensum { get; set; }
        public string anioPensum { get; set; }
        public string descripcion { get; set; }
        public int idCarrera { get; set; }
        public int limiteCreditoTrimestral { get; set; }
        public bool esActivo { get; set; }
    }
}
