//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pensum
    {
        public int idPensum { get; set; }
        public string nombrePensum { get; set; }
        public string anioPensum { get; set; }
        public string descripcion { get; set; }
        public int idCarrera { get; set; }
        public int limiteCreditoTrimestral { get; set; }
        public bool esActivo { get; set; }
    }
}
