//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudesSoporte
    {
        public int idSolicitud { get; set; }
        public int idUsuario { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public int idEstatus { get; set; }
        public System.DateTime FechaUltimoEstatus { get; set; }
        public int idAsignadoA { get; set; }
        public string Respuesta { get; set; }
    }
}
