//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudesSoporte
    {
        public int idSolicitud { get; set; }
        public int idUsuario { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public int idEstatus { get; set; }
        public System.DateTime FechaUltimoEstatus { get; set; }
        public int idAsignadoA { get; set; }
        public string Respuesta { get; set; }
    }
}
